app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/



Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');


	Route::get('/', function () {
	    return view('layouts.app');

	});

	Route::get('/admin', function () {
	    return view('layouts.admin');
	});

	//LEAGUES 
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource('leagues','LeaguesController');
	});

	Route::get('/admin/leagues/{id}/destroy',[
		'uses' => 'LeaguesController@destroy',
		'as' => 'admin.leagues.destroy'
		]);

	//END LEAGUES

	//PLAYERS
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource('players','PlayersController');
	});

	Route::get('/admin/players/store/{id}','PlayersController@store');

	Route::get('/admin/players/{id}/destroy',[
		'uses' => 'PlayersController@destroy',
		'as' => 'admin.players.destroy'
		]);

	//END PLAYERS

	//CLUBS
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource('clubs','clubsController');
	});
	
	Route::get('/admin/clubs/{id}/destroy',[
		'uses' => 'clubsController@destroy',
		'as' => 'admin.clubs.destroy'
	]);
	//END CLUBS

	//CATEGORIES 
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource('categories','CategoriesController');
	});

	Route::get('/admin/categories/{id}/destroy',[
		'uses' => 'CategoriesController@destroy',
		'as' => 'admin.categories.destroy'
		]);

	//END CATEGORIES 

	//INSCRIPTIONS
	Route::group(['prefix' => 'admin'], function () {
		
	    Route::resource('inscriptions','InscriptionsController');
	});
	
	Route::get('/admin/inscriptions/{id}/destroy',[
		'uses' => 'InscriptionsController@destroy',
		'as' => 'admin.inscriptions.destroy'
	]);

	Route::get('/admin/club/players/{id}', 'ClubsController@players');
	//END INSCRIPTIONS

	Route::get('/admin/enConstruccion', function () {
		 return View('enConstruccion');
	});

	//IADMINS
	Route::group(['prefix' => 'admin'], function () {
		
	    Route::resource('admins','adminsController');
	});
	
	Route::get('/admin/admins/{id}/destroy',[
		'uses' => 'adminsController@destroy',
		'as' => 'admin.admins.destroy'
	]);
	//END ADMINS

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'Categories';
    protected $fillable = ['id','name'];
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Category;

use Laracasts\Flash\Flash;

use Session;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return View('categories.index')->with('categories',$categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('categories.templeate');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category($request->all());
        $category->save();
        
        Flash::info('El category se ha creado correctamente');
        return redirect()->route('admin.categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $category = category::find($id);
        return view('categories.templeate')->with('category',$category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        $category->fill($request->all());
        $category->save();
        Flash::info('El Category se ha editado correctamente');
        return redirect('/admin/categories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();
        Flash::info('El category se ha eliminado correctamente');
        return redirect('/admin/categories')->with('success','noticia');
    }
}

resources/views/categories/index.blade.php
@extends('layouts.admin')

@section('titleContent')
<h2>Lista <strong>Categorias</strong></h2>
@endsection
@section('titlePanel')
<h3 class="panel-title"><strong>Lista </strong>Categoria</h3>
@endsection
@section('content')
<div class="col-md-12 col-sm-12 col-xs-12">
	<div class="panel-content pagination2 table-responsive" >
		<table class="table table-hover table-dynamic">
          	<thead>
              	<tr>
	                <th>ID Categoria</th>
	                <th>Nombre</th>
	                <th class="text-center">Fecha Inicio</th>
	                <th class="text-center">Fecha Fin</th>
	                
	                <th class="text-center">Acciones</th>
              	</tr>
            </thead>
          	<tbody> 
          		@foreach($categories as $category)                 
          		<tr>
	                <td>{{ $category->id }}</td>
                  	<td>{{ $category->name }}</td>
                  	<td>{{ $category->created_at }}</td>
                    <td>{{ $category->updated_at }}</td>
                 	
                  	
                  	<td>
                      	<div class="text-center dropdown" id="user-header">
                        	<button type="button" class="btn btn-sm btn-primary" aria-expanded="false"href="#" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                          		<i class="glyphicon glyphicon-th-list">&nbsp;</i><span class="caret"></span>
                        	</button>
	                        <ul class="dropdown-menu">
	                          
	                          <li>
	                            <a href="{{ route('admin.categories.edit', $category->id)}}"><i class="glyphicon glyphicon-edit"></i><span>Editar</span></a>
	                          </li>
	                          <li>
	                            <a href="{{ route('admin.categories.destroy', $category->id)}}"><i  class="glyphicon glyphicon-remove"></i><span>Borrar</span></a>
	                          </li>
	                        </ul>
                     	</div>
                    </td>
                </tr>
                @endforeach
            </tbody>    
        </table>   
        
    </div>
</div>
             


  
@endsection
@section('scripts')



@endsection

resources/views/categories/templeate.blade.php
@extends('layouts.admin')

@section('titleContent')
<h2><strong>Categorias</strong></h2>
@endsection
@section('titlePanel')
<h3 class="panel-title"><strong>Categoria </strong>{{ isset($category) ? $category->name : null }}</h3>
@endsection
@section('content')

<div class="col-md-12 col-sm-12 col-xs-12">
  @if( isset($category) ) 
  	{!! Form::open(['route' => ['admin.categories.update', $category], 'id'=>'formCategory', 'method' => 'PUT', 'class' => 'form-horizontal', 'role' => 'form', 'files' => true ]) !!}
  @else
  {!! Form::open(['route' => 'admin.categories.store', 'id'=>'formCategory', 'method' => 'POST', 'class' => 'form-horizontal', 'role' => 'form', 'files' => true ]) !!}
    
  @endif	
    <div class="row">
  		<div class="col-md-6 col-sm-6 col-xs-6">
  			<div class="form-group">
		      <label class="col-sm-3 control-label">Equipo<span class="text-danger">*</span>
		      </label>
		      <div class="col-sm-9 prepend-icon">
		        <input type="text" name="name" value="{{ isset($category) ? $category->name : null }}"  class="form-control" placeholder="Minimo 3 caracteres ..." minlength="3" required>
		        <i class="fa fa-bookmark"></i>
		      </div>
		    </div>
		    
  		</div>
  		<div class="col-md-6 col-sm-6 col-xs-6">
  		</div>
  	</div>
    
    <div class="row">
      <div class="col-sm-9 col-sm-offset-3">
        <div class="pull-right">
          <button type="submit" class="btn btn-embossed btn-primary m-r-20">Guardar</button>
          <button type="reset" class="cancel btn btn-embossed btn-default m-b-10 m-r-0">Cancelar</button>
        </div>
      </div>
    </div>
  {!! Form::close() !!}
</div>
             


  
@endsection
@section('scripts')

<script src="{{ asset('plugins/bootstrap-tags-input/bootstrap-tagsinput.min.js')}}"></script> <!-- Select Inputs -->
	<script src="{{ asset('plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script> <!-- >Bootstrap Date Picker -->
	<script src="{{ asset('plugins/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js')}}"></script> <!-- >Bootstrap Date Picker in Spanish (can be removed if not use) -->
<script src="{{asset('js/plugins/tags/tagsinput.min.js')}}"></script>
<script src="{{asset('plugins/jquery-validation/jquery.validate.js')}}"></script>
<script src="{{asset('plugins/jquery-validation/additional-methods.min.js')}}"></script>
<script src="{{asset('plugins/jquery-validation/src/localization/messages_es.js')}}"></script>
<script src="{{asset('plugins/bootstrap-filestyle-1.2.1/src/bootstrap-filestyle.min.js')}}"></script>

<script>
$(document).ready(function() {
  $("#formCategory").validate({
    lang: 'es'  // or whatever language option you have.
  });
});

</script>
@endsection