app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/



Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');


	Route::get('/', function () {
	    return view('layouts.app');

	});

	Route::get('/admin', function () {
	    return view('layouts.admin');
	});

	//LEAGUES 
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource('leagues','LeaguesController');
	});

	Route::get('/admin/leagues/{id}/destroy',[
		'uses' => 'LeaguesController@destroy',
		'as' => 'admin.leagues.destroy'
		]);

	//END LEAGUES

	//PLAYERS
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource('players','PlayersController');
	});

	Route::get('/admin/players/store/{id}','PlayersController@store');

	Route::get('/admin/players/{id}/destroy',[
		'uses' => 'PlayersController@destroy',
		'as' => 'admin.players.destroy'
		]);

	//END PLAYERS

	//CLUBS
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource('clubs','clubsController');
	});
	
	Route::get('/admin/clubs/{id}/destroy',[
		'uses' => 'clubsController@destroy',
		'as' => 'admin.clubs.destroy'
	]);
	//END CLUBS

	//CATEGORIES 
	Route::group(['prefix' => 'admin'], function () {
	    Route::resource('categories','CategoriesController');
	});

	Route::get('/admin/categories/{id}/destroy',[
		'uses' => 'CategoriesController@destroy',
		'as' => 'admin.categories.destroy'
		]);

	//END CATEGORIES 

	//INSCRIPTIONS
	Route::group(['prefix' => 'admin'], function () {
		
	    Route::resource('inscriptions','InscriptionsController');
	});
	
	Route::get('/admin/inscriptions/{id}/destroy',[
		'uses' => 'InscriptionsController@destroy',
		'as' => 'admin.inscriptions.destroy'
	]);

	Route::get('/admin/club/players/{id}', 'ClubsController@players');
	//END INSCRIPTIONS

	Route::get('/admin/enConstruccion', function () {
		 return View('enConstruccion');
	});

	//IADMINS
	Route::group(['prefix' => 'admin'], function () {
		
	    Route::resource('admins','adminsController');
	});
	
	Route::get('/admin/admins/{id}/destroy',[
		'uses' => 'adminsController@destroy',
		'as' => 'admin.admins.destroy'
	]);
	//END ADMINS

});

resources/views/layouts/admin.blade.php
  <!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="admin-themes-lab">
    <meta name="author" content="themes-lab">
    <link rel="shortcut icon" href="{{ asset('images/favicon.png')}}" type="image/png">
    <title>Sistema de Campeonatos</title>
    <link href="{{ asset('css/style.css')}}" rel="stylesheet">
    <link href="{{ asset('css/theme.css')}}" rel="stylesheet">
    <link href="{{ asset('css/ui.css')}}" rel="stylesheet">
    <script src="{{ asset('plugins/modernizr/modernizr-2.6.2-respond-1.1.0.min.js') }}"></script>
    <!-- BEGIN PAGE STYLE -->
    
    
    <!-- END PAGE STYLE -->
    
  </head>
  <!-- LAYOUT: Apply "submenu-hover" class to body element to have sidebar submenu show on mouse hover -->
  <!-- LAYOUT: Apply "sidebar-collapsed" class to body element to have collapsed sidebar -->
  <!-- LAYOUT: Apply "sidebar-top" class to body element to have sidebar on top of the page -->
  <!-- LAYOUT: Apply "sidebar-hover" class to body element to show sidebar only when your mouse is on left / right corner -->
  <!-- LAYOUT: Apply "submenu-hover" class to body element to show sidebar submenu on mouse hover -->
  <!-- LAYOUT: Apply "fixed-sidebar" class to body to have fixed sidebar -->
  <!-- LAYOUT: Apply "fixed-topbar" class to body to have fixed topbar -->
  <!-- LAYOUT: Apply "rtl" class to body to put the sidebar on the right side -->
  <!-- LAYOUT: Apply "boxed" class to body to have your page with 1200px max width -->

  <!-- THEME STYLE: Apply "theme-sdtl" for Sidebar Dark / Topbar Light -->
  <!-- THEME STYLE: Apply  "theme sdtd" for Sidebar Dark / Topbar Dark -->
  <!-- THEME STYLE: Apply "theme sltd" for Sidebar Light / Topbar Dark -->
  <!-- THEME STYLE: Apply "theme sltl" for Sidebar Light / Topbar Light -->
  
  <!-- THEME COLOR: Apply "color-default" for dark color: #2B2E33 -->
  <!-- THEME COLOR: Apply "color-primary" for primary color: #319DB5 -->
  <!-- THEME COLOR: Apply "color-red" for red color: #C9625F -->
  <!-- THEME COLOR: Apply "color-green" for green color: #18A689 -->
  <!-- THEME COLOR: Apply "color-orange" for orange color: #B66D39 -->
  <!-- THEME COLOR: Apply "color-purple" for purple color: #6E62B5 -->
  <!-- THEME COLOR: Apply "color-blue" for blue color: #4A89DC -->
  <!-- BEGIN BODY -->
  <body class="fixed-topbar fixed-sidebar theme-sdtl color-default">
    <!--[if lt IE 7]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <section>
      <!-- BEGIN SIDEBAR -->
        @extends('layouts.menu')
      <!-- END SIDEBAR -->
      <div class="main-content">
        <!-- BEGIN TOPBAR -->
        @extends('layouts.head')
         
         
        <!-- END TOPBAR -->
        <!-- BEGIN PAGE CONTENT -->
        <div class="page-content">
          @include('flash::message')
          <div class="header">
            @yield('titleContent')
            <!--<h2>Lista <strong>Paneles</strong></h2>-->
            <div class="breadcrumb-wrapper">
              <!--@extends('layouts.bread')
              <ol class="breadcrumb">
                <li><a href="#">Make</a>
                </li>
                <li><a href="#">Pages</a>
                </li>
                <li class="active">Buttons</li>
              </ol>-->
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 portlets">
              <div class="panel panel-default no-bd">
                <div class="panel-header bg-dark">
                  @yield('titlePanel')
                  <!--<h3 class="panel-title"><strong>Agregar </strong>nuevo panel</h3>-->
                </div>

                <div class="panel-content bg-white">
                  <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                      @if(count($errors)>0)

                        <div class="alert alert-danger">Errores
                          <ul>
                            @foreach($errors->all() as $error)
                              <li>{{ $error }}</li>
                            @endforeach
                          </ul>
                        </div>
                      @endif
                      @yield('content')
                      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="footer">
            <div class="copyright">
              <p class="pull-left sm-pull-reset">
                <span> <span class="copyright"></span>2016</span>
                <span>RIVER SRL</span>.
                <span>Todos los derechos reservados. </span>
              </p>
              <p class="pull-right sm-pull-reset">
                <span><a href="#" class="m-r-10">Soporte</a> | <a href="#" class="m-l-10 m-r-10">Terminos de uso</a> | <a href="#" class="m-l-10">Politicas de Privacidad</a></span>
              </p>
            </div>
          </div>
        </div>
        
        <!-- END PAGE CONTENT -->
      </div>
      <!-- END MAIN CONTENT -->
      
    </section>
    <!-- BEGIN QUICKVIEW SIDEBAR -->
  
    <!-- END QUICKVIEW SIDEBAR -->
    <!-- BEGIN SEARCH -->
    
 
    <!-- END SEARCH -->
    <!-- BEGIN PRELOADER -->
    <div class="loader-overlay">
      <div class="spinner">
        <div class="bounce1"></div>
        <div class="bounce2"></div>
        <div class="bounce3"></div>
      </div>
    </div>
    <!-- END PRELOADER -->
    <a href="#" class="scrollup"><i class="fa fa-angle-up"></i></a> 
    <script src="{{ asset('plugins/jquery/jquery-1.11.1.min.js')}}"></script>
    <script src="{{ asset('plugins/jquery/jquery-migrate-1.2.1.min.js')}}"></script>
    <script src="{{ asset('plugins/jquery-ui/jquery-ui-1.11.2.min.js')}}"></script>
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="{{ asset('plugins/jquery-cookies/jquery.cookies.min.js')}}"></script> <!-- Jquery Cookies, for theme -->
    <script src="{{ asset('plugins/jquery-block-ui/jquery.blockUI.min.js')}}"></script> <!-- simulate synchronous behavior when using AJAX -->
    <script src="{{ asset('plugins/translate/jqueryTranslator.min.js')}}"></script> <!-- Translate Plugin with JSON data -->
    <script src="{{ asset('plugins/mcustom-scrollbar/jquery.mCustomScrollbar.concat.min.js')}}"></script> <!-- Custom Scrollbar sidebar -->
    <script src="{{ asset('plugins/bootstrap-dropdown/bootstrap-hover-dropdown.min.js')}}"></script> <!-- Show Dropdown on Mouseover -->
    <script src="{{ asset('js/application.js')}}"></script> <!-- Main Application Script -->
    <script src="{{ asset('js/plugins.js')}}"></script> <!-- Main Plugin Initialization Script -->
    
    
    <!-- BEGIN PAGE SCRIPT -->
    <script src="{{ asset('plugins/noty/jquery.noty.packaged.min.js')}}"></script>  <!-- Notifications -->
    <!-- END PAGE SCRIPT -->
    <!-- BEGIN TABLA SCRIPT -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js')}}"></script> <!-- Tables Filtering, Sorting & Editing -->
    
     @yield('scripts')
    
  </body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Sistema de Campeonatos</title>

    <!-- Fonts -->
    <link href="{{ asset('css/style.css')}}" rel="stylesheet">
    <link href="{{ asset('css/theme.css')}}" rel="stylesheet">
    <link href="{{ asset('css/ui.css')}}" rel="stylesheet">
    <script src="{{ asset('plugins/modernizr/modernizr-2.6.2-respond-1.1.0.min.js') }}"></script>
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body class="account" data-page="login">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Sistema de Campeonatos
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                  <!--  <li><a href="{{ url('/home') }}">Home</a></li>-->
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Autenticarse</a></li>
                        <!--<li><a href="{{ url('/register') }}">Register</a></li>-->
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="{{ asset('plugins/jquery/jquery-1.11.1.min.js')}}"></script>
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="{{ asset('plugins/backstretch/backstretch.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-validation/src/localization/messages_es.js')}}"></script>  
    <script type="text/javascript" src="{{ asset('js/login.js')}}"></script>

    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}

</body>
</html>

resources/views/layouts/bread.blade.php
<ol class="breadcrumb">
  <li><a href="#">Make</a>
  </li>
  <li><a href="#">Pages</a>
  </li>
  <li class="active">Buttons</li>
</ol>

resources/views/layouts/footer.blade.php
<div class="footer">
  <div class="copyright">
    <p class="pull-left sm-pull-reset">
      <span> <span class="copyright"></span>2015</span>
      <span>THEMES LAB</span>.
      <span>All rights reserved. </span>
    </p>
    <p class="pull-right sm-pull-reset">
      <span><a href="#" class="m-r-10">Support</a> | <a href="#" class="m-l-10 m-r-10">Terms of use</a> | <a href="#" class="m-l-10">Privacy Policy</a></span>
    </p>
  </div>
</div>

resources/views/layouts/login.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Centralita</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta content="" name="description" />
        <meta content="themes-lab" name="author" />
        <link rel="shortcut icon" href="{{ asset('images/logo/logo-dark.png')}}">
        <link href="{{ asset('css/style.css')}}" rel="stylesheet">
        <link href="{{ asset('css/ui.css')}}" rel="stylesheet">
        <link href="{{ asset('plugins/bootstrap-loading/lada.min.css')}}" rel="stylesheet">
        
    </head>
    <body class="account" data-page="login">
        <!-- BEGIN LOGIN BOX -->
        <div class="container" id="login-block">
            <div class="row">
                <div class="col-sm-6 col-md-4 col-md-offset-4">
                    <div class="account-wall">
                        <i class="user-img icons-faces-users-03"></i>
                        <form class="ladda-button" action="#" method="post" id="login" enctype="multipart/form-data" data-style="zoom-out">
                            <div class="form-group append-icon">
                                <input id="user" data-type="text" type="text" name="name" id="name" class="form-control form-white username" placeholder="Username" required>
                                <i class="icon-user"></i>
                            </div>
                            <div class="form-group append-icon m-b-20">
                                <input id="password" data-type="text" type="password" name="password" class="form-control form-white password" placeholder="Password" required>
                                <i class="icon-lock"></i>
                            </div>
                            <button id="submitlogin" onClick="login('login','login', 'login', 'login')" class="btn btn-lg btn-blue btn-block ladda-button" data-style="expand-left">Sign In</button>
                           
                            <div class="clearfix">
                                <p class="pull-left m-t-20"><a id="password" href="#">Forgot password?</a></p>
                            </div>
                        </form>
                        <form class="form-password" role="form">
                                
                        </form>
                            
                        <div id="salida"></div>
                    </div>
                </div>
            </div>
            <p class="account-copyright">
                <span>Copyright © 2016  </span><span>Centralita</span>.<span> All rights reserved.</span>
            </p>
            
        </div>
        <script src="{{ asset('plugins/jquery/jquery-1.11.1.min.js')}}"></script>
        <script src="{{ asset('plugins/jquery/jquery-migrate-1.2.1.min.js')}}"></script>
        <script src="{{ asset('plugins/gsap/main-gsap.min.js')}}"></script>
        <script src="{{ asset('plugins/bootstrap/js/bootstrap.min.js')}}"></script>
        <script src="{{ asset('plugins/backstretch/backstretch.min.js')}}"></script>
        <script src="{{ asset('plugins/bootstrap-loading/lada.min.js')}}"></script>
        <script src="{{ asset('plugins/noty/jquery.noty.packaged.min.js')}}"></script>  <!-- Notifications -->
       
        <script type="text/javascript" src="{{ asset('js/login.js')}}"></script>
        <!-- BEGIN PAGE SCRIPTS -->
        <script src="{{ asset('plugins/jquery-validation/jquery.validate.js')}}"></script> <!-- Form Validation -->
        <script src="{{ asset('plugins/jquery-validation/additional-methods.min.js')}}"></script> <!-- Form Validation Additional Methods - OPTIONAL -->
    </body>
</html>

resources/views/layouts/menu.blade.php
<!-- BEGIN SIDEBAR -->

<div class="sidebar">
   <div class="logopanel">
      <h1><a href="dashboard.html">&nbsp;</a></h1>
   </div>
   <div class="sidebar-inner">
      <div class="text-center sidebar-top">
         <!--<form action="#" method="post" class="searchform" id="search-results">
            <input type="text" class="form-control" name="keyword" placeholder="Search here...">
         </form>-->
         <div class="userlogged clearfix">
            <i class="fa fa-soccer-ball-o"></i>
            <div class="user-details">
               <h4></h4>
               <!--<div class="dropdown user-login">
                  <button class="btn btn-xs dropdown-toggle btn-rounded" type="button" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" data-delay="300">
                  <i class="online"></i><span>Available</span><i class="fa fa-angle-down"></i>
                  </button>
                  <ul class="dropdown-menu">
                     <li><a href="#"><i class="busy"></i><span>Busy</span></a></li>
                     <li><a href="#"><i class="turquoise"></i><span>Invisible</span></a></li>
                     <li><a href="#"><i class="away"></i><span>Away</span></a></li>
                  </ul>
               </div>-->
            </div>
         </div>
      </div>
      <div class="menu-title">
         <span>Navegacion</span> 
      </div>
      <ul class="nav nav-sidebar">
         <li class="tm nav-active nav-parent">
            <a href="dashboard.php"><i class="icon-home"></i><span>Inicio</span></a>
            <ul class="children collapse" style=""></ul>
         </li>
         
         <!--<li class="tm nav-parent">
            <a href="#"><i class="icon icons-seo-icons-15"></i><span>Agentes</span><span class="fa arrow"></span></a>
            <ul class="children collapse" style="">
               <li class=""><a href="agentes.php">Lista</a></li>
               <li class=""><a href="grupos.php">Grupos</a></li>
            </ul>
         </li>-->
         <li class="tm nav-parent">
            <a href=""><i class="fa fa-flag-checkered"></i><span>Campeonatos</span> <span class="fa arrow"></span></a>
            <ul class="children collapse" style="">
               <li class=""><a href="{{ route('admin.leagues.index')}}">Lista de Campeonatos</a></li>
               <li class=""><a href="{{ url('/admin/leagues/create')}}">Nuevo Campeonato</a></li>
           </ul>
         </li>
         <li class="tm nav-parent" style="position: relative; opacity: 1; z-index: 0;">
            <a href=""><i class="fa fa-shield"></i><span>Clubs</span> <span class="fa arrow"></span></a>
            <ul class="children collapse" style="">
               <li class="" style="opacity: 1; z-index: 0;"><a href="{{ route('admin.clubs.index')}}">Lista de Clubs</a></li>
               <li class=""><a href="{{ url('/admin/clubs/create')}}">Nuevo Club</a></li>
            </ul>
         </li>
         <li class="tm nav-parent">
            <a href="#"><i class="fa fa-group"></i><span>Jugadores</span><span class="fa arrow"></span></a>
            <ul class="children collapse" style="">
               <li class=""><a href="{{ route('admin.players.index')}}">Lista de jugadores</a></li>
               <li class=""><a href="{{ url('/admin/players/create')}}">Nuevo Jugador</a></li>
            </ul>
         </li>
         <li class="tm nav-parent">
            <a href="#"><i class="fa fa-bookmark"></i><span>Categorias</span><span class="fa arrow"></span></a>
            <ul class="children collapse" style="">
               <li class=""><a href="{{ route('admin.categories.index')}}">Lista de Categorias</a></li>
               <li class=""><a href="{{ url('/admin/categories/create')}}">Nueva Categoria</a></li>
            </ul>
         </li>
         <li class="tm nav-parent">
            <a href="#"><i class="fa fa-file-text-o"></i><span>Inscripciones</span><span class="fa arrow"></span></a>
            <ul class="children collapse" style="">
               <li class=""><a href="{{ route('admin.inscriptions.index')}}">Lista de Inscripciones</a></li>
               <li class=""><a href="{{ route('admin.inscriptions.create')}}">Nueva Inscripcion</a></li>
            </ul>
         </li>
         <li class="tm nav-parent">
            <a href="#"><i class="fa fa-file-text-o"></i><span>Administradores</span><span class="fa arrow"></span></a>
            <ul class="children collapse" style="">
               <li class=""><a href="{{ route('admin.admins.index')}}">Lista de Administradores</a></li>
               <li class=""><a href="{{ route('admin.admins.create')}}">Nuevo Administrador</a></li>
            </ul>
         </li>
         <li class="tm nav-parent">
            <a href="#"><i class="fa fa-file-text-o"></i><span>Resultados</span><span class="fa arrow"></span></a>
            <ul class="children collapse" style="">
               <li class=""><a href="{{ url('/admin/enConstruccion')}}">Lista de Formularios</a></li>
               <li class=""><a href="{{ url('/admin/enConstruccion')}}">Nuevo Formulario</a></li>
            </ul>
         </li>
         <li class="tm nav-parent" style="position: relative; opacity: 1; z-index: 0;">
            <a href=""><i class="fa fa-bar-chart-o"></i><span>Reportes</span> <span class="fa arrow"></span></a>
            <ul class="children collapse" style="">
               <li class=""><a href="{{ url('/admin/enConstruccion')}}">Reporte 1</a></li>
               <li class=""><a href="{{ url('/admin/enConstruccion')}}">Reporte 2</a></li>
               
            </ul>
         </li>        
      </ul>

      <div class="sidebar-footer clearfix" style="">
         <a class="pull-left footer-settings" href="#" data-rel="tooltip" data-placement="top" data-original-title="Settings">
         <i class="icon-settings"></i></a>
         <a class="pull-left toggle_fullscreen" href="#" data-rel="tooltip" data-placement="top" data-original-title="Fullscreen">
         <i class="icon-size-fullscreen"></i></a>
         <a class="pull-left" href="#" data-rel="tooltip" data-placement="top" data-original-title="Lockscreen">
         <i class="icon-lock"></i></a>
         <a class="pull-left btn-effect" href="#" data-modal="modal-1" data-rel="tooltip" data-placement="top" data-original-title="Logout">
         <i class="icon-power"></i></a>
      </div>
   </div>
</div>
<!-- END SIDEBAR -->